# Pre-commit hooks configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
        pass_filenames: false
        always_run: true

      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --staged --verbose --redact
        language: system
        pass_filenames: false
